Add Publish State permission
statamic-rad-pack/runway pull request #553
Opened 2024-07-09 22:49 UTC by edalzell

Matching the `canManagePublishState` from core and replicating this PR: https://github.com/statamic/cms/pull/10424

2024-07-09 22:50 UTC, edalzell commented
@duncanmcclean let's talk about this one, as I believe we'd need a migration script otherwise it's breaking.

2024-07-10 08:38 UTC, duncanmcclean commented
> let's talk about this one, as I believe we'd need a migration script otherwise it's breaking.

Yes, we'd either need to ship with an upgrade script or include this PR in the next breaking changes release (which'll have the nested fields fix).

2024-07-10 11:20 UTC, duncanmcclean requested changes

2024-07-10 11:20 UTC, duncanmcclean commented on src/ServiceProvider.php
> +                                    Permission::make("publish {$resource->handle()}")
The concept of "publish states" are opt-in, so we probably only want to add this permission if they're enabled for the resource.

```php
if ($resource->hasPublishStates()) {
    Permission::make("publish {$resource->handle()}")
        ->label("Manage {$resource->handle()} Publish State"),
}
```

2024-07-10 11:20 UTC, duncanmcclean commented on resources/js/components/Publish/PublishForm.vue
> +                    <span v-text="this.canManagePublishState ? __('Publish') : __('Create Revision')" />
Like we've done in Core, can we extract this out into a `publishButtonText` method?

2024-07-10 11:20 UTC, duncanmcclean commented on resources/js/components/Publish/PublishForm.vue
Related to [my comment here](https://github.com/statamic/cms/pull/10424#discussion_r1672091778), you updated the text of multiple buttons in this PR, but only updated one button in your Core PR.

Is there any particular reason for this?

2024-07-12 16:08 UTC, duncanmcclean approved these changes

2024-07-12 16:09 UTC, merged